name: "Release dev container features & Generate Documentation"
on:
  workflow_run:
    workflows: ["CI - Test Features"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main') || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: "Publish Features"
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./src"
          generate-docs: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & Push Documentation
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Check for changes
          if [[ -n $(git status --porcelain) ]]; then
            echo "Documentation changes detected. Committing..."
            git add src/**/README.md
            git commit -m "docs: automated update [skip ci]"
            git push origin HEAD:main
          else
            echo "No documentation changes."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
